spring:
  datasource:
    url: jdbc:mysql://localhost:3307/kim-container
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wkdandud12
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  profiles:
    include: aws

cache:
  expiry:
    minutes: 5
  size: 100

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none

logging:
  level:
    com.example: DEBUG

